### ISSUE TITLE
error executing the pipeline - Response: {"error":"unauthorized","error_description":"Bad credentials"}

### ISSUE THREAD

**Issue by betht1220** [crdant/cf-mgmt-demo#1]
Hi Chuck - hope you're still watching this github.
I've followed instruction but running cf-mgmt pipeline gives me following error. I've looked and looked again over my configuration, but could not find anything odd.
Can you just glance at it, and let me know what is amissed.
Here's my vars.yml
           git_repo_uri: https://github.com/tranb/cf-mgmt-demo
           git_repo_branch: demo
           system_domain: dev.cfdev.sh #your cf system domain
           user_id: cf-mgmt 
           password: not used
           client_secret: cf-mgmt-secret # client secret for uaac for user_id
           ldap_password: password 
          log_level: INFO # logging level for cf-mgmt commands in the pipeline
LDAP login with admin/password is working fine
Here's token get with the cf-mgmt account and it returns token
        "uaac token client get cf-mgmt -s cf-mgmt-secret" 
Here's error
2019/01/09 16:52:27 W0109 16:52:27.715996 15 initialize.go:72] Password parameter is deprecated, create uaa client and client-secret instead
error: Error getting token: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"unauthorized","error_description":"Bad credentials"}

**Comment by crdant** [comment]
Hi Beth,

Sorry I was busy all day today mentoring at a hackathon. Did you close
because you worked through it? I should have some cycles on Friday to take
a look.

Chuck

**Comment by betht1220** [comment]
Hello Chuck, yes, I was able to resolve the issue.  It is in .envrc that I need to give pw a value ""; otherwise, I'll get error.
Everything works Chuck, thank you so much for providing this demo.
